name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: App Settings Variable subsitution
        uses: microsoft/variable-substitution@v1
        with:
          files: './pdt.svc/appsettings.json'
        env:
          SearchEngine.SearchResultsMax: '50'
          SearchEngine.GoogleCustomSearchCx: ${{env.GOOGLE_CUSTOM_SEARCH_CX}}
          SearchEngine.GoogleCustomSearchApiKey: ${{env.GOOGLE_CUSTOM_SEARCH_API_KEY}}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./pdt.svc/Dockerfile
          push: true
          tags: mtmazurik/pdt-svc:latest
